[package]
name = "attr-rs"
version = "0.1.0"
authors = ["Nick Hackman <snickhackman@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6"
proc-macro2 = "0.4"

[dependencies.syn]
features = ["full"]
version = "0.15"

[lib]
proc-macro = true
